apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "$schema": "https://www.krakend.io/schema/krakend.json",
      "version": 3,
      "name": "KrakenD - API Gateway",
      "extra_config": {
        "security/cors": {
          "allow_origins": ["*"],
          "expose_headers": ["Content-Length"],
          "max_age": "12h",
          "allow_methods": ["GET", "HEAD", "POST", "PUT", "DELETE", "PATCH"]
        },
        "telemetry/logging": {
          "level": "INFO",
          "prefix": "[KRAKEND]",
          "syslog": false,
          "stdout": true,
          "format": "default",
          "syslog_facility": "local3"
        }
      },
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "output_encoding": "json",
      "debug_endpoint": true,
      "echo_endpoint": true,
      "endpoints": []
    }
