apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deploy
  labels:
    name: krakend-deploy
    app: local-app
spec:
  template:
    metadata:
      name: krakend-pod
      labels:
        name: krakend-pod
        app: local-app
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:watch
          ports:
            - containerPort: 8080
          # imagePullPolicy: Never
          command: ["/usr/bin/krakend"]
          args: ["run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080"]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: KRAKEND_PORT
              value: "8080"
          volumeMounts:
            - name: krakend-persistent-storage
              mountPath: /etc/krakend
        - name: krakend-designer
          image: krakend/designer
          ports:
            - containerPort: 8081
      volumes:
        - name: krakend-persistent-storage
          hostPath:
            path: /Users/duongson/Desktop/Kubernetes/volumes/krakend

  replicas: 1
  selector:
    matchLabels:
      name: krakend-pod
      app: local-app
