apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  type: NodePort
  ports:
    - name: krakend-http
      port: 8080
      targetPort: 8080
      nodePort: 30880
      protocol: TCP
    - name: krakend-designer-http
      port: 8081
      targetPort: 8081
      nodePort: 30881
      protocol: TCP
  selector: # label data of the port
    name: krakend-pod
    app: local-app
