apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8080
      protocol: TCP
  selector: # label data of the port
    name: krakend-pod
    app: local-app
