apiVersion: v1
kind: Service
metadata:
  name: krakend
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector: # label data of the port
    name: krakend-pod
    app: local-app
