apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    name: pgadmin-service
    app: local-app
spec:
  type: NodePort
  ports:
    - targetPort: 80 #default value is port - this is POD port
      port: 80 # service port
      nodePort: 30801
  selector: # label data of the port
    name: pgadmin-pod
    app: local-app
