apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: local-app
spec:
  type: NodePort
  ports:
    - targetPort: 6379 #default value is port - this is POD port
      port: 6379 # service port
      nodePort: 36379
  selector: # label data of the port
    name: mysql-pod
    app: local-app
