apiVersion: apps/v1 #Version of Kubernetes API to create object
kind: Deployment #type of object to create
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: local-app
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: local-app
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /Users/duongson/Desktop/Kubernetes/volumes/mysql
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: local-app
