apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql-pod
    app: local-app
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
          port: 3306
          nodePort: 33006
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      hostPath:
        path: ./Desktop/Kubernetes/volumes/mysql
