apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - targetPort: 3306 #default value is port - this is POD port
      port: 3306 # service port
      nodePort: 30306
  selector: # label data of the port
    name: mysql-pod
    app: local-app
