apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
  - targetPort: 5432 #default value is port - this is POD port
    port: 5432 # service port
  selector: # label data of the port
    name: postgres-pod
    app: demo-voting-app
