apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
  - targetPort: 6379 #default value is port - this is POD port
    port: 6379 # service port
  selector: # label data of the port
    name: redis-pod
    app: demo-voting-app
