apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - targetPort: 80 #default value is port - this is POD port
    port: 80 # service port
    nodePort: 30005
  selector: # label data of the port
    name: result-app-pod
    app: demo-voting-app
