apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    name: kafka-pod
    app: local-app
spec:
  containers:
    - name: kafka
      image: bitnami/kafka
      ports:
        - containerPort: 9092
