apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - targetPort: 80 #default value is port - this is POD port
    port: 80 # service port
    nodePort: 30008 #range 30000 - 32767 - port to communicate externally
  selector: # label data of the port
    app: myapp
    type: front-end
